#ifndef __type_description_interfaces__msg__TypeDescription__idl__
#define __type_description_interfaces__msg__TypeDescription__idl__

#include "type_description_interfaces/msg/./IndividualTypeDescription_.idl"
module type_description_interfaces
{
  module msg
  {
    module dds
    {

      /**
       * Represents a complete type description, including the type itself as well as the types it references.
       */
      @TypeCode(type="type_description_interfaces::msg::dds_::TypeDescription_")
      struct TypeDescription
      {
        /**
         * Description of the type.
         */
        type_description_interfaces::msg::dds::IndividualTypeDescription type_description;
        /**
         * Descriptions of all referenced types, recursively.
         */
        sequence<type_description_interfaces::msg::dds::IndividualTypeDescription> referenced_type_descriptions;
      };
    };
  };
};

#endif
