#ifndef __shape_msgs__msg__SolidPrimitive__idl__
#define __shape_msgs__msg__SolidPrimitive__idl__

#include "geometry_msgs/msg/./Polygon_.idl"
module shape_msgs
{
  module msg
  {
    module dds
    {
      const octet BOX =
      1;

      const octet SPHERE =
      2;

      const octet CYLINDER =
      3;

      const octet CONE =
      4;

      const octet PRISM =
      5;

      /**
       * For type BOX, the X, Y, and Z dimensions are the length of the corresponding sides of the box.
       */
      const octet BOX_X =
      0;

      const octet BOX_Y =
      1;

      const octet BOX_Z =
      2;

      /**
       * For the SPHERE type, only one component is used, and it gives the radius of the sphere.
       */
      const octet SPHERE_RADIUS =
      0;

      const octet CYLINDER_HEIGHT =
      0;

      const octet CYLINDER_RADIUS =
      1;

      const octet CONE_HEIGHT =
      0;

      const octet CONE_RADIUS =
      1;

      const octet PRISM_HEIGHT =
      0;


      /**
       * Defines box, sphere, cylinder, cone and prism.
       * All shapes are defined to have their bounding boxes centered around 0,0,0.
       * The meaning of the shape dimensions: each constant defines the index in the 'dimensions' array.
       * For the CYLINDER and CONE types, the center line is oriented along the Z axis.
       * Therefore the CYLINDER_HEIGHT (CONE_HEIGHT) component of dimensions gives the
       * height of the cylinder (cone).
       * The CYLINDER_RADIUS (CONE_RADIUS) component of dimensions gives the radius of
       * the base of the cylinder (cone).
       * Cone and cylinder primitives are defined to be circular. The tip of the cone
       * is pointing up, along +Z axis.
       * For the type PRISM, the center line is oriented along Z axis.
       * The PRISM_HEIGHT component of dimensions gives the
       * height of the prism.
       * The polygon defines the Z axis centered base of the prism.
       * The prism is constructed by extruding the base in +Z and -Z
       * directions by half of the PRISM_HEIGHT
       * Only x and y fields of the points are used in the polygon.
       * Points of the polygon are ordered counter-clockwise.
       */
      @TypeCode(type="shape_msgs::msg::dds_::SolidPrimitive_")
      struct SolidPrimitive
      {
        /**
         * The type of the shape
         */
        octet type;
        /**
         * The dimensions of the shape
         * At no point will dimensions have a length > 3.
         */
        sequence<double, 3> dimensions;
        geometry_msgs::msg::dds::Polygon polygon;
      };
    };
  };
};

#endif
