//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.18 at 10:40:23 AM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eprosima.xmlschemas.fastrtps_profiles;
