//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.eprosima.xmlschemas.fastrtps_profiles;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for profilesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profilesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;choice>
 *           &lt;element name="domainparticipant_factory" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}domainParticipantFactoryProfileType" maxOccurs="unbounded"/>
 *           &lt;element name="participant" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}participantProfileType" maxOccurs="unbounded"/>
 *           &lt;element name="data_writer" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}publisherProfileType" maxOccurs="unbounded"/>
 *           &lt;element name="data_reader" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}subscriberProfileType" maxOccurs="unbounded"/>
 *           &lt;element name="transport_descriptors" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}TransportDescriptorListType"/>
 *           &lt;element name="topic" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}topicProfileType" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profilesType", propOrder = {
    "domainparticipantFactoryOrParticipantOrDataWriter"
})
public class ProfilesType {

    @XmlElements({
        @XmlElement(name = "domainparticipant_factory", type = DomainParticipantFactoryProfileType.class),
        @XmlElement(name = "participant", type = ParticipantProfileType.class),
        @XmlElement(name = "data_writer", type = PublisherProfileType.class),
        @XmlElement(name = "data_reader", type = SubscriberProfileType.class),
        @XmlElement(name = "transport_descriptors", type = TransportDescriptorListType.class),
        @XmlElement(name = "topic", type = TopicProfileType.class)
    })
    protected List<Object> domainparticipantFactoryOrParticipantOrDataWriter;

    /**
     * Gets the value of the domainparticipantFactoryOrParticipantOrDataWriter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainparticipantFactoryOrParticipantOrDataWriter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainparticipantFactoryOrParticipantOrDataWriter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainParticipantFactoryProfileType }
     * {@link ParticipantProfileType }
     * {@link PublisherProfileType }
     * {@link SubscriberProfileType }
     * {@link TransportDescriptorListType }
     * {@link TopicProfileType }
     * 
     * 
     */
    public List<Object> getDomainparticipantFactoryOrParticipantOrDataWriter() {
        if (domainparticipantFactoryOrParticipantOrDataWriter == null) {
            domainparticipantFactoryOrParticipantOrDataWriter = new ArrayList<Object>();
        }
        return this.domainparticipantFactoryOrParticipantOrDataWriter;
    }

}
