//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.eprosima.xmlschemas.fastrtps_profiles;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for publishModeQosPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="publishModeQosPolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="kind" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}publishModeQosKindPolicyType"/>
 *         &lt;element name="flow_controller_name" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "publishModeQosPolicyType", propOrder = {

})
public class PublishModeQosPolicyType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PublishModeQosKindPolicyType kind;
    @XmlElement(name = "flow_controller_name")
    protected String flowControllerName;

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link PublishModeQosKindPolicyType }
     *     
     */
    public PublishModeQosKindPolicyType getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishModeQosKindPolicyType }
     *     
     */
    public void setKind(PublishModeQosKindPolicyType value) {
        this.kind = value;
    }

    /**
     * Gets the value of the flowControllerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowControllerName() {
        return flowControllerName;
    }

    /**
     * Sets the value of the flowControllerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowControllerName(String value) {
        this.flowControllerName = value;
    }

}
