//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.18 at 10:40:23 AM CST 
//


package com.eprosima.xmlschemas.fastrtps_profiles;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reliabilityQosPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reliabilityQosPolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="kind" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}reliabilityQosKindPolicyType" minOccurs="0"/>
 *         &lt;element name="max_blocking_time" type="{http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles}durationType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reliabilityQosPolicyType", propOrder = {

})
public class ReliabilityQosPolicyType {

    @XmlSchemaType(name = "string")
    protected ReliabilityQosKindPolicyType kind;
    @XmlElement(name = "max_blocking_time")
    protected DurationType maxBlockingTime;

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link ReliabilityQosKindPolicyType }
     *     
     */
    public ReliabilityQosKindPolicyType getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReliabilityQosKindPolicyType }
     *     
     */
    public void setKind(ReliabilityQosKindPolicyType value) {
        this.kind = value;
    }

    /**
     * Gets the value of the maxBlockingTime property.
     * 
     * @return
     *     possible object is
     *     {@link DurationType }
     *     
     */
    public DurationType getMaxBlockingTime() {
        return maxBlockingTime;
    }

    /**
     * Sets the value of the maxBlockingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationType }
     *     
     */
    public void setMaxBlockingTime(DurationType value) {
        this.maxBlockingTime = value;
    }

}
