#ifndef __builtin_interfaces__msg__Time__idl__
#define __builtin_interfaces__msg__Time__idl__

module builtin_interfaces
{
  module msg
  {
    module dds
    {

      /**
       * This message communicates ROS Time defined here:
       * https://design.ros2.org/articles/clock_and_time.html
       */
      @TypeCode(type="builtin_interfaces::msg::dds_::Time_")
      struct Time
      {
        /**
         * The seconds component, valid over all int32 values.
         */
        long sec;
        /**
         * The nanoseconds component, valid in the range [0, 1e9).
         */
        unsigned long nanosec;
      };
    };
  };
};

#endif
