#ifndef __lifecycle_msgs__msg__State__idl__
#define __lifecycle_msgs__msg__State__idl__

module lifecycle_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Indicates state has not yet been set.
       */
      const octet PRIMARY_STATE_UNKNOWN =
      0;

      /**
       * This is the life cycle state the node is in immediately after being
       * instantiated.
       */
      const octet PRIMARY_STATE_UNCONFIGURED =
      1;

      /**
       * This state represents a node that is not currently performing any processing.
       */
      const octet PRIMARY_STATE_INACTIVE =
      2;

      /**
       * This is the main state of the node's life cycle. While in this state, the node
       * performs any processing, responds to service requests, reads and processes
       * data, produces output, etc.
       */
      const octet PRIMARY_STATE_ACTIVE =
      3;

      /**
       * The finalized state is the state in which the node ends immediately before
       * being destroyed.
       */
      const octet PRIMARY_STATE_FINALIZED =
      4;

      /**
       * In this transition state the node's onConfigure callback will be called to
       * allow the node to load its configuration and conduct any required setup.
       */
      const octet TRANSITION_STATE_CONFIGURING =
      10;

      /**
       * In this transition state the node's callback onCleanup will be called to clear
       * all state and return the node to a functionally equivalent state as when
       * first created.
       */
      const octet TRANSITION_STATE_CLEANINGUP =
      11;

      /**
       * In this transition state the callback onShutdown will be executed to do any
       * cleanup necessary before destruction.
       */
      const octet TRANSITION_STATE_SHUTTINGDOWN =
      12;

      /**
       * In this transition state the callback onActivate will be executed to do any
       * final preparations to start executing.
       */
      const octet TRANSITION_STATE_ACTIVATING =
      13;

      /**
       * In this transition state the callback onDeactivate will be executed to do any
       * cleanup to start executing, and reverse the onActivate changes.
       */
      const octet TRANSITION_STATE_DEACTIVATING =
      14;

      /**
       * This transition state is where any error may be cleaned up.
       */
      const octet TRANSITION_STATE_ERRORPROCESSING =
      15;


      /**
       * Primary state definitions as depicted in:
       * http://design.ros2.org/articles/node_lifecycle.html
       * These are the primary states. State changes can only be requested when the
       * node is in one of these states.
       * Temporary intermediate states. When a transition is requested, the node
       * changes its state into one of these states.
       */
      @TypeCode(type="lifecycle_msgs::msg::dds_::State_")
      struct State
      {
        /**
         * The state id value from the above definitions.
         */
        octet id;
        /**
         * A text label of the state.
         */
        string label;
      };
    };
  };
};

#endif
