#ifndef __lifecycle_msgs__msg__Transition__idl__
#define __lifecycle_msgs__msg__Transition__idl__

module lifecycle_msgs
{
  module msg
  {
    module dds
    {
      /**
       * This transition will instantiate the node, but will not run any code beyond
       * the constructor.
       */
      const octet TRANSITION_CREATE =
      0;

      /**
       * The node's onConfigure callback will be called to allow the node to load its
       * configuration and conduct any required setup.
       */
      const octet TRANSITION_CONFIGURE =
      1;

      /**
       * The node's callback onCleanup will be called in this transition to allow the
       * node to load its configuration and conduct any required setup.
       */
      const octet TRANSITION_CLEANUP =
      2;

      /**
       * The node's callback onActivate will be executed to do any final preparations
       * to start executing.
       */
      const octet TRANSITION_ACTIVATE =
      3;

      /**
       * The node's callback onDeactivate will be executed to do any cleanup to start
       * executing, and reverse the onActivate changes.
       */
      const octet TRANSITION_DEACTIVATE =
      4;

      /**
       * This signals shutdown during an unconfigured state, the node's callback
       * onShutdown will be executed to do any cleanup necessary before destruction.
       */
      const octet TRANSITION_UNCONFIGURED_SHUTDOWN =
      5;

      /**
       * This signals shutdown during an inactive state, the node's callback onShutdown
       * will be executed to do any cleanup necessary before destruction.
       */
      const octet TRANSITION_INACTIVE_SHUTDOWN =
      6;

      /**
       * This signals shutdown during an active state, the node's callback onShutdown
       * will be executed to do any cleanup necessary before destruction.
       */
      const octet TRANSITION_ACTIVE_SHUTDOWN =
      7;

      /**
       * This transition will simply cause the deallocation of the node.
       */
      const octet TRANSITION_DESTROY =
      8;

      /**
       * Reserved [10-69], private transitions
       * These transitions are not publicly available and cannot be invoked by a user.
       * The following transitions are implicitly invoked based on the callback
       * feedback of the intermediate transition states.
       */
      const octet TRANSITION_ON_CONFIGURE_SUCCESS =
      10;

      const octet TRANSITION_ON_CONFIGURE_FAILURE =
      11;

      const octet TRANSITION_ON_CONFIGURE_ERROR =
      12;

      const octet TRANSITION_ON_CLEANUP_SUCCESS =
      20;

      const octet TRANSITION_ON_CLEANUP_FAILURE =
      21;

      const octet TRANSITION_ON_CLEANUP_ERROR =
      22;

      const octet TRANSITION_ON_ACTIVATE_SUCCESS =
      30;

      const octet TRANSITION_ON_ACTIVATE_FAILURE =
      31;

      const octet TRANSITION_ON_ACTIVATE_ERROR =
      32;

      const octet TRANSITION_ON_DEACTIVATE_SUCCESS =
      40;

      const octet TRANSITION_ON_DEACTIVATE_FAILURE =
      41;

      const octet TRANSITION_ON_DEACTIVATE_ERROR =
      42;

      const octet TRANSITION_ON_SHUTDOWN_SUCCESS =
      50;

      const octet TRANSITION_ON_SHUTDOWN_FAILURE =
      51;

      const octet TRANSITION_ON_SHUTDOWN_ERROR =
      52;

      const octet TRANSITION_ON_ERROR_SUCCESS =
      60;

      const octet TRANSITION_ON_ERROR_FAILURE =
      61;

      const octet TRANSITION_ON_ERROR_ERROR =
      62;

      /**
       * The transition callback successfully performed its required functionality.
       */
      const octet TRANSITION_CALLBACK_SUCCESS =
      97;

      /**
       * The transition callback failed to perform its required functionality.
       */
      const octet TRANSITION_CALLBACK_FAILURE =
      98;

      /**
       * The transition callback encountered an error that requires special cleanup, if
       * possible.
       */
      const octet TRANSITION_CALLBACK_ERROR =
      99;


      /**
       * Default values for transitions as described in:
       * http://design.ros2.org/articles/node_lifecycle.html
       * Reserved [0-9], publicly available transitions.
       * When a node is in one of these primary states, these transitions can be
       * invoked.
       * Reserved [90-99]. Transition callback success values.
       * These return values ought to be set as a return value for each callback.
       * Depending on which return value, the transition will be executed correctly or
       * fallback/error callbacks will be triggered.
       * #
       * # Fields
       * #
       */
      @TypeCode(type="lifecycle_msgs::msg::dds_::Transition_")
      struct Transition
      {
        /**
         * The transition id from above definitions.
         */
        octet id;
        /**
         * A text label of the transition.
         */
        string label;
      };
    };
  };
};

#endif
