name: Run Gradle test (all platforms)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-12, macos-14]
        os: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1
      - name: Run tests
        run: |
          gradle compositeTask -PtaskName=test -PrunningOnCIServer=true -Dorg.gradle.jvmargs="-Xmx4G"
      - name: Publish Test Report - ${{ inputs.test-category }}
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
